# -*- coding: utf-8 -*-
"""Cópia de atividadeprof-igor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQq9a0Co9ovvyPXonWI6Qeg73A_DvZJl

Atividade do dia 04/10/2024

1. Soma de dois números: Peça ao usuário dois números e mostre a soma deles.
"""

Numero1 = int(input("Digite um numero: "))
Numero2 = int(input("Digite outro numero: "))
Soma = Numero1 + Numero2

print(Soma)

"""#2. Subtração de dois números: Peça ao usuário dois números e mostre a subtração do primeiro pelo segundo.


"""

Numero1 = int(input("Digite um numero: "))
Numero2 = int(input("Digite outro numero: "))
Subtracao = Numero1 - Numero2

print(Subtracao)

"""#3. Multiplicação de dois números: Peça ao usuário dois números e mostre o resultado da multiplicação entre eles.

"""

Numero1 = int(input("Digite um numero: "))
Numero2 = int(input("Digite outro numero: "))
Multiplicacao = Numero1 * Numero2

print(Multiplicacao)

"""#4. Divisão de dois números: Peça ao usuário dois números e mostre o resultado da divisão do primeiro pelo segundo.



"""

Numero1 = int(input("Digite um numero: "))
Numero2 = int(input("Digite outro numero: "))
Divisao = Numero1 / Numero2

print(Divisao)

"""# 5. Resto da divisão: Peça dois números inteiros e mostre o resto da divisão entre eles.

"""

Numero1 = float(input("Digite um numero: "))
Numero2 = float(input("Digite outro numero: "))
Resto = Numero1 % Numero2

print(Resto)

"""#6. Potência de um número: Peça um número e um expoente, e mostre o resultado do número elevado a esse expoente.



"""

NumeroA = int(input("Digite numeroA:"))
NumeroB = int(input("Digite numeroB:"))
Potencia = NumeroA ** NumeroB

print(Potencia)

"""#7. Média de três números: Peça três números e mostre a média deles."""

media1 = float(input("Digite a primeira nota: "))
media2 = float(input("Digite a segunda nota: "))
media3 = float(input("Digite a terceira nota: "))

media = (media1 + media2 + media3) / 3

print(media)

"""#8. Conversão de temperatura: Converta uma temperatura em graus Celsius para Fahrenheit usando a fórmula:
F=95C+32F = \frac{9}{5}C + 32F=59C+32


"""

graus = int(input("Digite a temperantura em grau celsius: "))
fahrenheit = (9/5)*graus + 32


print(fahrenheit)

"""
#9. Conversão de moeda: Peça um valor em reais e mostre o valor convertido em dólares.Considere uma taxa de conversão fixa.

"""

valor_Real = float(input("Digite o valor em R$: "))
valor_Dolar = float(5.59)
taxa_Conversao = valor_Real / valor_Dolar

print(f"O valor em dólar é: ${taxa_Conversao:.2f}")

"""#10. Área de um retângulo: Peça a largura e a altura de um retângulo e calcule a área"""

laegura_retangulo = int (input("Digite a largura do retangulo:"))
altura_retangulo = int (input("Digite a altura do retangulo: "))
area_retangulo = laegura_retangulo * altura_retangulo

print(f"A área do retangulo é: {area_retangulo}")

"""#11. Perímetro de um quadrado: Peça o lado de um quadrado e calcule o perímetro (soma dos lados)

"""

lado_quadrado = int(input("Digite o lado do quadrado: "))
perimetro_quadrado = lado_quadrado * 4

print(f"O perímetro do quadrado é: {perimetro_quadrado}")

"""#12. Área de um triângulo: Peça a base e a altura de um triângulo e calcule a área usando a fórmula: Aˊrea=base×altura2\text{Área} = \frac{\text{base} \times \text{altura}}{2}Aˊrea=2base×altura

"""

base_triangulo = float(input("Digite a base do triangulo: "))
altura_triangulo = float(input("Digite a altura do triangulo: "))
area_triangulo = (base_triangulo * altura_triangulo) / 2

print(f"A área do triangulo é: {area_triangulo}")

"""#13. Área de um círculo: Peça o raio de um círculo e calcule a área usando a fórmula:
Aˊrea=πr2\text{Área} = \pi r^2Aˊrea=πr2
(Use o valor aproximado de π = 3.14159).
"""

area_Circulo = float(input("Digite a area do circulo: "))
raio_Circulo = float(input("Digite o raio do circulo: "))
pi = 3.14159
area_Circulo = pi * (raio_Circulo ** 2)

print(f"A área do circulo é: {area_Circulo}")

"""#14. Conversão de metros para centímetros: Peça um valor em metros e converta para centímetros.

"""

# Solicitar o valor em metros
metros = float(input("Digite o valor em metros: "))

# Converter metros para centímetros
centimetros = metros * 100

# Exibir o resultado
print(f"{metros} metros equivalem a {centimetros} centímetros.")

"""#15. Cálculo de horas trabalhadas: Peça a quantidade de horas trabalhadas e o valor por hora, e calcule o salário total.

"""

#Quantidade de horas
quantidade_horas = float(input("Digite a quantidade de horas trabalhadas: "))
valor_por_hora=float(input("Digite o valor por hora: "))
horas_trabalhadas = float(input("Digite o número de horas trabalhadas: "))

# Calcular o valor por hora
valor_por_hora = quantidade_horas / horas_trabalhadas
salario_total = quantidade_horas * valor_por_hora

# Exibir o salário total com 3 casas decimais
print(f"O salário total é: R$ {salario_total:.3f}")

"""#16. Preço com desconto: Peça o preço de um produto e o percentual de desconto, e mostre o preço final com desconto aplicado."""

# Solicitar o preço do produto e o percentual de desconto
preço_do_produto = float(input("Digite o preço do produto: "))
percentual_do_desconto = float(input("Digite o percentual de desconto: "))


# Calcular o preço com desconto
preço_com_desconto = preço_do_produto * (1 - percentual_do_desconto / 100)

# Exibir o preço com desconto
print(f"O preço com desconto é: R$ {preço_com_desconto:.2f}")



"""#17. Calcular a velocidade média: Peça a distância percorrida e o tempo gasto, e calcule a velocidade média usando a fórmula: v=distaˆnciatempov = \frac{\text{distância}}{\text{tempo}}v=tempodistaˆncia

"""

distância_percorrida = float(input("Digite a distância percorrida: "))
tempo_gasto = float(input("Digite o tempo gasto: "))

# Calcular a velocidade média
velocidade_média = distância_percorrida / tempo_gasto

# Exibir o resultado
print(f"A velocidade média é: {velocidade_média:.2f} km/h")

"""#18. Converter idade em dias: Peça a idade de uma pessoa em anos e converta para dias.Desconsidere anos bissextos.


"""

# Peça a idade de uma pessoa em anos e converta para dias.
idade_pessoa = int(input("Digite sua idade: "))
idade_em_dias = idade_pessoa * 365

# Exibir o resultado
print(f"A idade em dias é: {idade_em_dias} dias")

"""#19. Quantidade de segundos em um dia: Calcule quantos segundos existem em um dia (24 horas).


"""

# Cálculo de segundos em um dia
calcule_segundos = 24 * 60 * 60

# Exibir o resultado
print(f"Existem {calcule_segundos} segundos em um dia.")

"""
#20. Calcular o IMC (Índice de Massa Corporal): Peça o peso (em kg) e a altura (em metros), e calcule o IMC usando a fórmula:
IMC=pesoaltura2\text{IMC} = \frac{\text{peso}}{\text{altura}^2}IMC=altura2peso

"""

# Calcular o IMC (Índice de Massa Corporal)
peso_pessoa = float(input("Digite seu peso (kg): "))
altura_pessoa = float(input("Digite sua altura (m): "))
imc = peso_pessoa / (altura_pessoa ** 2)

# Exibir o resultado do IMC
print(f"O IMC é: {imc:.2f}")

"""#21. Diferença entre dois números: Peça dois números e mostre a diferença absoluta entre eles (sem sinal negativo).

"""

# Solicitar dois números do usuário
escolha_numeros1 = int(input("Digite um o primeiro numero: "))
escolha_numeros2 = int(input("Digite um o segundo  numero: "))
diferenca_absoluta = abs(escolha_numeros1 - escolha_numeros2)


# Calcular a diferença absoluta
print(f"A diferença absoluta entre os números é: {diferenca_absoluta}")

"""#22. Divisão inteira de dois números: Peça dois números inteiros e mostre o resultado da divisão inteira (sem considerar o resto).

"""

#Peca o usario que digite o numero
numero1 = int(input("Digite o primeiro número: "))
numero2 = int(input("Digite o segundo número: "))

# Calcule a divisão inteira
divisao_inteira = numero1 // numero2


# Exiba o resultado
print(f"O resultado da divisão inteira entre {numero1} e {numero2} é: {divisao_inteira}")

"""#23. Valor absoluto de um número: Peça um número e mostre seu valor absoluto.

"""

numero_absoluto = int(input("Digite um número: "))
valor_absoluto = abs(numero_absoluto)

print(f"O valor absoluto do número é: {valor_absoluto}")

"""#24. Converter km/h para m/s: Peça uma velocidade em km/h e converta para m/s. Use a fórmula:
velocidade em m/s=velocidade em km/h3.6\text{velocidade em m/s} =
\frac{\text{velocidade em km/h}}{3.6}velocidade em m/s=3.6velocidade em km/h
"""

#Peça uma velocidade em km/h
velocidade_km_h =float(input("Digite a velocidade em km/h: "))
velocidade_m_s = velocidade_km_h / 3.6

#
print(f"A velocidade em m/s é: {velocidade_m_s:.2f}")

"""#25. Fórmula de Bhaskara: Peça os coeficientes aaa, bbb e ccc de uma equação do segundo grau e calcule as raízes usando a fórmula de Bhaskara

"""

# Fórmula de Bhaskara:
coeficientes_aaa = float(input("Digite o coeficiente a: "))
coeficientes_bbb = float(input("Digite o coeficiente b: "))
coeficientes_ccc = float(input("Digite o coeficiente c: "))

calcular = (coeficientes_bbb ** 2) - (4 * coeficientes_aaa * coeficientes_ccc)

#
a = coeficientes_aaa
b = coeficientes_bbb
c = coeficientes_ccc


#
if calcular >= 0:
    print("Esta equação não possui raízes reais.")
    raiz1 = (-b + math.sqrt(calcular)) / (2*coeficientes_aaa)
    raiz2 = (-b - math.sqrt(calcular)) / (2*coeficientes_aaa)
    if calcular == 0:
        print(f"A equação tem uma única raiz: {raiz1:.2f}")
    else:
        print(f"As raízes da equação são: {raiz1:.2f} e {raiz2:.2f}")
else:
    print("A equação não possui raízes reais.")

"""#26. Valor total de uma compra: Peça o preço de três produtos e calcule o valor total da compra

"""

preço_do_produto_Arroz = float(input("Digite o preço do primeiro produto: "))
preço_do_produto_Feijao = float(input("Digite o preço do segundo produto: "))
preço_do_produto_Oleo = float(input("Digite o preço do terceiro produto: "))

 #calcular produto
preço_do_produto_Arroz =35
preço_do_produto_Feijao = 7
preço_do_produto_Oleo = 6


valor_total = preço_do_produto_Arroz + preço_do_produto_Feijao + preço_do_produto_Oleo

if valor_total <= 500:
    pass # Adicione a lógica a ser executada se o valor total for menor ou igual a 500
    print(f"O valor total da compra é: R$ {valor_total:.2f}")

"""#27. Converter dias para semanas e dias: Peça um valor em dias e converta para semanas e dias (por exemplo, 10 dias = 1 semana e 3 dias)
.
"""

dias =int(input("Digite a quantidade de dias: "))
semanas = dias // 7
dias_restantes = dias % 7

print(f"{dias} dias equivalem a {semanas} semanas e {dias_restantes} dias.")

"""#28. Desconto progressivo: Peça o valor de uma compra e aplique um desconto de 5% se o valor for maior que R$100 e , e de 10% se for maior que R$500.
, e de 10% se for maior que R$500.

"""

total_da_compra = float(input("Digite o valor total da compra:"))
desconto = 0

# Aplicar o desconto correspondente
if total_da_compra > 100:
    desconto = total_da_compra * 0.05

if total_da_compra > 500:
    desconto = total_da_compra * 0.10
total_da_compra = total_da_compra - desconto

print(f"O valor do desconto é: R$ {desconto:.2f} e o valor final da compra foi de R$ {total_da_compra:.2f}")

"""#29. Divisão com casas decimais limitadas: Peça dois números e mostre o resultado da divisão com apenas duas casas decimais"""

#Escreva os numeros
numero1 = float(input("Digite o primeiro numero:"))
numero2 = float(input("Digite o segundo numero:"))

numero1 * numero2

print(f"O resultado da divisão é: {numero1 / numero2:.2f}")